# Generated by Django 2.1.2 on 2018-11-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
